services:
  hostmint:
    image: ghcr.io/jehudme/hostmint:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hostmint-postgresql:5432/hostMint
      - SPRING_DATASOURCE_USERNAME=hostMint
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://hostmint-postgresql:5432/hostMint
      - SPRING_ELASTICSEARCH_URIS=http://hostmint-elasticsearch:9200
      - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${JWT_SECRET}
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/management/health']
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      hostmint-postgresql:
        condition: service_healthy
      hostmint-elasticsearch:
        condition: service_healthy

  hostmint-postgresql:
    image: postgres:17.3
    environment:
      - POSTGRES_USER=hostMint
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=hostMint
    volumes:
      - hostmint_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hostMint']
      interval: 5s
      timeout: 5s
      retries: 10

  hostmint-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - hostmint_es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200/_cluster/health?wait_for_status=green&timeout=10s']
      interval: 5s
      timeout: 10s
      retries: 10

  prometheus:
    image: prom/prometheus:v3.10.0
    volumes:
      - prometheus_data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  alertmanager:
    image: prom/alertmanager:v0.31.1
    volumes:
      - alertmanager_data:/alertmanager
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:12.4.1
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  prometheus_data: {}
  grafana_data: {}
  hostmint_db_data: {}
  hostmint_es_data: {}
  alertmanager_data: {}

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 10s
      scrape_configs:
        - job_name: 'hostmint'
          metrics_path: '/management/prometheus'
          static_configs:
            - targets: ['hostmint:8080']
  alertmanager_config:
    content: |
      route:
        group_by: ['alertname']
        receiver: 'web.hook'
      receivers:
        - name: 'web.hook'
          webhook_configs:
            - url: 'http://127.0.0.1:5001/'
