# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDljMzc3MTJkN2JlYzQ0MTZjZDgzMjk2YWNiMWJjMjAxNzZhMTA2Mjk4NjdmNTZkNWE2MzNlMmFhOTFlNTQyMDU3MDMyNTE5OWVmNjI5NjAwM2VkMDUzYTFmYzc3YjhhZTgwMzZmYzVjNjdhOWIwYTBkYmRiZGY1OTQ1MWY1NzQ=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: HostMint
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: HostMint
    password:
