# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDIxZDFlYWY2ZTgwNDJiYWJhOTI5NDk3YTA2NGI3YTVhZTIzMmVkMTczNTZkMGNmZjc2MjYyNDY5Y2Y5MGZhYzRkMTc4MjZlZjAyMWM4MWIwZWZmZjAyYzdhMGE1NGIyNWZhMDkwZTc3ODhmZTljZTY4NjI5NWZmMzg3ODZjMzk=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: hostMint
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: hostMint
    password:
