#common configuration shared between all applications
configserver:
  name: Service Registry
  status: Connected to Consul running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjJhYzkxZTEyMDMxZTNmYjdmMjZhM2I4MzEyZmNlM2RmNGZkMGU2NzFlNDg0MTI0NDVhMWU4YjAyZWRjNTQ2NmExNDFjNjk2YTc4YmJiZGYyYTczNWE2ZjRhYTk0ZTZmOWNjZQ==
