package com.hostmint.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequestLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestLogAllPropertiesEquals(RequestLog expected, RequestLog actual) {
        assertRequestLogAutoGeneratedPropertiesEquals(expected, actual);
        assertRequestLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestLogAllUpdatablePropertiesEquals(RequestLog expected, RequestLog actual) {
        assertRequestLogUpdatableFieldsEquals(expected, actual);
        assertRequestLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestLogAutoGeneratedPropertiesEquals(RequestLog expected, RequestLog actual) {
        assertThat(actual)
            .as("Verify RequestLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestLogUpdatableFieldsEquals(RequestLog expected, RequestLog actual) {
        assertThat(actual)
            .as("Verify RequestLog relevant properties")
            .satisfies(a -> assertThat(a.getCorrelationId()).as("check correlationId").isEqualTo(expected.getCorrelationId()))
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()))
            .satisfies(a -> assertThat(a.getPath()).as("check path").isEqualTo(expected.getPath()))
            .satisfies(a -> assertThat(a.getStatusCode()).as("check statusCode").isEqualTo(expected.getStatusCode()))
            .satisfies(a -> assertThat(a.getDurationMs()).as("check durationMs").isEqualTo(expected.getDurationMs()))
            .satisfies(a -> assertThat(a.getPrincipal()).as("check principal").isEqualTo(expected.getPrincipal()))
            .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
            .satisfies(a -> assertThat(a.getErrorCode()).as("check errorCode").isEqualTo(expected.getErrorCode()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequestLogUpdatableRelationshipsEquals(RequestLog expected, RequestLog actual) {
        assertThat(actual)
            .as("Verify RequestLog relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
